const projectData={
  posiufo:{number:'PROJECT 01',title:'POSIUFO Store',tags:['Frontend','Project Management'],description:'Website toko online untuk POSIUFO, usaha produk kreatif yang menjual stiker, gantungan kunci, pin, dan pakaian. Proyek ini memadukan implementasi frontend dengan dokumentasi penutupan proyek pada mata kuliah Information System Project Management.',role:'Frontend Developer & Project Contributor',tools:'HTML, CSS, JavaScript',type:'Academic Project',highlights:['Katalog, kategori, dan pencarian produk','Keranjang belanja berbasis local storage','Responsive navigation dan halaman produk','Project closure sebagai dokumentasi evaluasi dan penyelesaian proyek'],note:'Project closure ditempatkan sebagai artefak pendukung untuk menunjukkan pemahaman siklus proyek, bukan sebagai proyek terpisah.',actions:[['Live Website','https://sa4turn.github.io/posiufo/'],['Repository','https://github.com/sa4turn/posiufo'],['Project Closure','https://docs.google.com/document/u/0/d/1FK2nsBFHjpATuJvR9Rr6ZHI0mworYKmsPCSoG_yf0Zo/mobilebasic']]},
  relonsApp:{number:'PROJECT 02',title:'RELONS Mobile Prototype',tags:['User Experience','Team Project'],description:'Prototype aplikasi pelaporan bullying untuk mahasiswa UMN yang dikembangkan pada mata kuliah User Experience. Prosesnya mencakup benchmark lima aplikasi, tinjauan literatur, wawancara narasumber, penyusunan kebutuhan, dan penerjemahan temuan ke alur produk.',role:'UX Prototype Contributor',tools:'Lovable, UX Research, Canva',type:'User Experience Coursework',highlights:['Riset dengan kerangka 5 aplikasi, 5 jurnal, dan 5 narasumber','Pelaporan anonim, unggah bukti, dan tracking status','Edukasi, forum dukungan, serta akses bantuan','Prototype dibuat melalui Lovable atas arahan dosen'],note:'Materi presentasi UX digunakan sebagai bukti proses dan keputusan desain, bukan ditampilkan sebagai proyek terpisah. Prototype ini merupakan proyek akademik, bukan kanal resmi UMN.',actions:[['Open Prototype','https://relons2.lovable.app/auth']]},
  relonsWeb:{number:'PROJECT 03',title:'RELONS Website',tags:['Web Development','Database Design'],description:'Implementasi website RELONS pada mata kuliah Web Design and Development. Versi web menerjemahkan konsep pelaporan bullying ke sistem berbasis Laravel dengan alur pengguna, pengelolaan laporan, dan basis data.',role:'Frontend & Database Design Contributor',tools:'HTML, Laravel, PHP, MySQL',type:'Web Design & Development Coursework',highlights:['Menyusun struktur halaman dan layout HTML','Menjaga tampilan sesuai rancangan dan kebutuhan bisnis','Merancang entitas serta relasi basis data','Mendukung autentikasi, laporan, bukti, forum, edukasi, dan tracking'],note:'Kontribusi dirumuskan langsung dari laporan akhir proyek. RELONS Website dan Mobile Prototype dipisahkan karena berasal dari dua mata kuliah dan luaran yang berbeda.',actions:[['Live Website','https://sa4turn.github.io/RELONS/'],['Repository','https://github.com/sa4turn/RELONS']]},
  melonku:{number:'PROJECT 04',title:'MelonKu',tags:['UI/UX Design','Team of 5'],description:'Konsep aplikasi mobile untuk membantu mendeteksi kematangan buah melon dan kondisi tanaman menggunakan teknologi computer vision.',role:'UI/UX & Prototype Contributor',tools:'Figma, Canva',type:'Academic Team Project',highlights:['Analisis kebutuhan dan konsep bisnis','Perancangan struktur aplikasi mobile','Desain antarmuka dan alur navigasi','Interactive prototype dikerjakan oleh Nur’Aini, Fariz, dan Zafran'],note:'Proyek dikembangkan oleh lima anggota. Bagian interactive prototype dikerjakan secara kolaboratif oleh tiga anggota tim.',actions:[['Figma Design','https://www.figma.com/design/X8ac7CqgnQ4bOGkFcU9tte/MelonKu?node-id=7-226']]},
  amalia:{number:'PROJECT 05',title:'Toko Amalia',tags:['Web System','Semester 2'],description:'Sistem informasi penjualan berbasis web untuk membantu operasional Toko Amalia. Sistem telah diimplementasikan dan digunakan selama periode proyek.',role:'System Designer & Developer',tools:'Figma, Web Technology',type:'IS321 Final Project',highlights:['Akses admin dan kasir','Pengelolaan produk dan bahan pokok','Pengelolaan data pemasok','Transaksi dan pencatatan data penjualan'],note:'Website pernah berfungsi, tetapi live demo dan source code tidak lagi tersedia setelah kehilangan data perangkat. Prototype Figma masih tersedia.',actions:[['Figma Prototype','https://www.figma.com/design/5OIZ0OqzVODptHC7Cyfz4i/Untitled?node-id=0-1&p=f']]},
  prisma:{number:'PROJECT 06',title:'PRISMA Unhas Content',tags:['Content Editing','Instagram Reels'],description:'Kontribusi editing konten video pendek untuk PRISMA Universitas Hasanuddin. Materi disusun ulang menjadi konten yang lebih ringkas, dinamis, dan sesuai ritme komunikasi media sosial.',role:'Video Content Editor',tools:'Video Editing, Social Media',type:'Content Collaboration',highlights:['Mengedit empat konten Instagram Reels','Menata pacing dan alur visual','Menyesuaikan materi untuk format vertikal','Menjaga penyampaian pesan tetap jelas dan engaging'],note:'Tautan karya mengarah langsung ke unggahan yang dipublikasikan oleh PRISMA Unhas.',actions:[['Reel 01','https://www.instagram.com/reel/Ddbo5xdTRog/'],['Reel 02','https://www.instagram.com/reel/DdYyyS4zrRO/'],['Reel 03','https://www.instagram.com/reel/Dc7O1OfTYjL/'],['Reel 04','https://www.instagram.com/reel/DcznSf8zC0c/']]},
  videoEditing:{number:'PROJECT 07',title:'Motion Editing Archive',tags:['Video Editing','Personal Archive'],description:'Arsip karya personal yang menunjukkan perkembangan kemampuan editing video melalui tiga fase alat dan gaya: Cute Cut Pro, Alight Motion, lalu Video Star.',role:'Video Editor',tools:'Cute Cut Pro, Alight Motion, Video Star',type:'Personal Creative Practice',highlights:['Eksplorasi cutting, pacing, dan sinkronisasi audio','Transisi dan motion editing','Eksperimen gaya visual lintas aplikasi','Tiga akun sebagai jejak perkembangan karya'],note:'Arsip ini diposisikan sebagai bukti keterampilan dan konsistensi eksplorasi kreatif, bukan pengalaman kerja profesional.',actions:[['Cute Cut Pro Era','https://www.instagram.com/nianaspie'],['Alight Motion Era','https://www.instagram.com/luvvkeii'],['Video Star Era','https://www.instagram.com/kawainiana']]},
  etika:{number:'PROJECT 08',title:'ETIKA 2021 Instagram Filter',tags:['AR Filter','Creative Technology'],description:'Filter Instagram yang dibuat untuk mendukung identitas visual dan interaksi peserta pada acara ETIKA 2021 Universitas Islam Indonesia.',role:'AR Filter Creator',tools:'Spark AR Studio',type:'Event Creative Project',highlights:['Konsep visual sesuai identitas acara','Pengembangan dan publikasi filter','Digunakan oleh lebih dari 50 peserta','Menjadi media interaksi digital selama acara'],note:'Source project lama sudah tidak tersedia, tetapi dokumentasi penggunaan filter pada acara masih tersimpan.',actions:[]},
  tiktok:{number:'PROJECT 09',title:'TikTok Effect Collection',tags:['Effect Design','Personal Project'],description:'Eksplorasi efek visual dan interaktif untuk TikTok yang dibuat serta dipublikasikan menggunakan Effect House.',role:'Effect Creator',tools:'TikTok Effect House',type:'Personal Exploration',highlights:['Efek IT Edition','Efek Love dan Bunny','Efek Simple','Beberapa efek telah digunakan dalam video pengguna TikTok'],note:'Proyek ini ditampilkan sebagai eksplorasi creative technology dan interactive media.',actions:[['Instagram Profile','https://instagram.com/nuraism_']]}
};

const canvas=document.querySelector('#stars');
const context=canvas.getContext('2d');
let stars=[];
function setCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(170,Math.floor(innerWidth/8))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.15,a:Math.random()*.65+.15,s:Math.random()*.08+.02}))}
function drawStars(){context.clearRect(0,0,innerWidth,innerHeight);stars.forEach(star=>{star.a+=star.s*(Math.random()>.5?1:-1);star.a=Math.max(.12,Math.min(.85,star.a));context.beginPath();context.arc(star.x,star.y,star.r,0,Math.PI*2);context.fillStyle=`rgba(210,226,255,${star.a})`;context.fill()});requestAnimationFrame(drawStars)}
setCanvas();drawStars();addEventListener('resize',setCanvas);

const words=['Frontend Explorer','Information Systems Student','UI/UX Learner','Creative Effect Maker'];let wordIndex=0,charIndex=0,deleting=false;const typingText=document.querySelector('#typingText');
function type(){const word=words[wordIndex];typingText.textContent=deleting?word.slice(0,--charIndex):word.slice(0,++charIndex);let delay=deleting?45:80;if(!deleting&&charIndex===word.length){deleting=true;delay=1350}else if(deleting&&charIndex===0){deleting=false;wordIndex=(wordIndex+1)%words.length;delay=350}setTimeout(type,delay)}
type();

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...document.querySelectorAll('.nav-link')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-40% 0px -50%'});sections.forEach(section=>sectionObserver.observe(section));

const menu=document.querySelector('#menuButton');const nav=document.querySelector('.floating-nav nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});navLinks.forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(button=>{button.classList.remove('active');button.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');document.querySelectorAll('.tab-panel').forEach(panel=>{const active=panel.dataset.panel===tab.dataset.tab;panel.classList.toggle('active',active);panel.hidden=!active})}));

const modal=document.querySelector('#projectModal');let lastFocus=null;
function openProject(key){const project=projectData[key];if(!project)return;lastFocus=document.activeElement;document.querySelector('#modalNumber').textContent=project.number;document.querySelector('#modalTags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');document.querySelector('#modalTitle').textContent=project.title;document.querySelector('#modalDescription').textContent=project.description;document.querySelector('#modalRole').textContent=project.role;document.querySelector('#modalTools').textContent=project.tools;document.querySelector('#modalType').textContent=project.type;document.querySelector('#modalHighlights').innerHTML=project.highlights.map(item=>`<li>${item}</li>`).join('');document.querySelector('#modalNote').textContent=project.note;document.querySelector('#modalActions').innerHTML=project.actions.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('');modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.modal-close').focus()}
function closeProject(){modal.hidden=true;document.body.style.overflow='';lastFocus?.focus()}
document.querySelectorAll('[data-open-project]').forEach(button=>button.addEventListener('click',()=>openProject(button.dataset.openProject)));document.querySelectorAll('[data-close-modal]').forEach(element=>element.addEventListener('click',closeProject));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeProject()});
document.querySelector('#year').textContent=new Date().getFullYear();
