const projectData={
  posiufo:{number:'PROJECT 01',title:'POSIUFO Store',tags:['Frontend','Project Management'],description:'An online store for POSIUFO, a creative-products business selling stickers, keychains, pins, and apparel. The project combines frontend implementation with project-closing documentation for the Information System Project Management course.',role:'Frontend Developer & Project Contributor',tools:'HTML, CSS, JavaScript',type:'Academic Project',highlights:['Product catalog, categories, and search','Local-storage shopping cart','Responsive navigation and product pages','Project closure documenting project evaluation and completion'],note:'The project closure is included as supporting material that demonstrates an understanding of the project lifecycle, rather than as a separate project.',actions:[['View Website','https://sa4turn.github.io/posiufo/'],['View Project Closure','https://docs.google.com/document/u/0/d/1FK2nsBFHjpATuJvR9Rr6ZHI0mworYKmsPCSoG_yf0Zo/mobilebasic']]},
  relonsApp:{number:'PROJECT 02',title:'RELONS Mobile Prototype',tags:['User Experience','Team Project'],description:'A bullying-reporting app prototype for UMN students, developed for a User Experience course. The process included benchmarking five apps, reviewing literature, interviewing participants, defining requirements, and translating the findings into a product flow.',role:'UX Prototype Contributor',tools:'Lovable, UX Research, Canva',type:'User Experience Coursework',highlights:['Research framework covering 5 apps, 5 journals, and 5 interviewees','Anonymous reporting, evidence uploads, and status tracking','Education, support forums, and access to help','Prototype created in Lovable under lecturer guidance'],note:'The UX presentation material demonstrates the process and design decisions rather than being presented as a separate project. This is an academic prototype, not an official UMN reporting channel.',actions:[['View Prototype','https://relons2.lovable.app/auth']]},
  relonsWeb:{number:'PROJECT 03',title:'RELONS Website',tags:['Web Development','Database Design'],description:'A RELONS website implementation created for the Web Design and Development course. The web version turns the bullying-reporting concept into a Laravel-based system with user flows, report management, and a database.',role:'Frontend & Database Design Contributor',tools:'HTML, Laravel, PHP, MySQL',type:'Web Design & Development Coursework',highlights:['Structured the pages and HTML layouts','Kept the interface aligned with the design and business requirements','Designed database entities and relationships','Supported authentication, reports, evidence, forums, education, and tracking'],note:'The contribution details come directly from the final project report. The RELONS Website and Mobile Prototype are shown separately because they were developed for different courses and produced different outcomes.',actions:[['View Website','https://sa4turn.github.io/RELONS/']]},
  melonku:{number:'PROJECT 04',title:'MelonKu',tags:['UI/UX Design','Team of 5'],description:'A mobile app concept designed to help detect melon ripeness and plant conditions using computer-vision technology.',role:'UI/UX & Prototype Contributor',tools:'Figma, Canva',type:'Academic Team Project',highlights:['Requirements and business-concept analysis','Mobile app structure design','Interface design and navigation flow','Interactive prototype created by Nur’Aini, Fariz, and Zafran'],note:'The project was developed by a five-person team. Three team members collaborated on the interactive prototype.',actions:[['View Figma Design','https://www.figma.com/design/X8ac7CqgnQ4bOGkFcU9tte/MelonKu?node-id=7-226']]},
  amalia:{number:'PROJECT 05',title:'Toko Amalia',tags:['Web System','Semester 2'],description:'A web-based sales information system developed to support Toko Amalia’s operations. The system was implemented and used during the project period.',role:'System Designer & Developer',tools:'Figma, Web Technology',type:'IS321 Final Project',highlights:['Admin and cashier access','Product and staple-goods management','Supplier data management','Transactions and sales-data recording'],note:'The website was previously functional, but the live demo and source code are no longer available after the device data was lost. The Figma prototype remains available.',actions:[['View Figma Prototype','https://www.figma.com/design/5OIZ0OqzVODptHC7Cyfz4i/Untitled?node-id=0-1&p=f']]},
  prisma:{number:'PROJECT 06',title:'PRISMA Unhas Content',tags:['Content Editing','Instagram Reels'],description:'A short-form video editing contribution for PRISMA at Hasanuddin University. The source material was reshaped into concise, dynamic content suited to the pace of social media communication.',role:'Video Content Editor',tools:'Video Editing, Social Media',type:'Content Collaboration',highlights:['Edited four Instagram Reels','Refined pacing and visual flow','Adapted the material for a vertical format','Kept the message clear and engaging'],note:'The work links lead directly to posts published by PRISMA Unhas.',actions:[['View Reel 01','https://www.instagram.com/reel/Ddbo5xdTRog/'],['View Reel 02','https://www.instagram.com/reel/DdYyyS4zrRO/'],['View Reel 03','https://www.instagram.com/reel/Dc7O1OfTYjL/'],['View Reel 04','https://www.instagram.com/reel/DcznSf8zC0c/']]},
  videoEditing:{number:'PROJECT 07',title:'Motion Editing Archive',tags:['Video Editing','Personal Archive'],description:'A personal archive showing the development of my video-editing skills across three tools and creative phases: Cute Cut Pro, Alight Motion, and Video Star.',role:'Video Editor',tools:'Cute Cut Pro, Alight Motion, Video Star',type:'Personal Creative Practice',highlights:['Explored cutting, pacing, and audio synchronization','Transitions and motion editing','Visual-style experiments across multiple apps','Three accounts documenting the evolution of the work'],note:'This archive demonstrates creative skills and consistent exploration rather than professional work experience.',actions:[['View Cute Cut Pro Work','https://www.instagram.com/nianaspie'],['View Alight Motion Work','https://www.instagram.com/luvvkeii'],['View Video Star Work','https://www.instagram.com/kawainiana']]},
  etika:{number:'PROJECT 08',title:'ETIKA 2021 Instagram Filter',tags:['AR Filter','Creative Technology'],description:'An Instagram filter created to support the visual identity and participant engagement of Universitas Islam Indonesia’s ETIKA 2021 event.',role:'AR Filter Creator',tools:'Spark AR Studio',type:'Event Creative Project',highlights:['Visual concept aligned with the event identity','Filter development and publication','Used by more than 50 participants','Provided a digital interaction medium during the event'],note:'The original source project is no longer available, but documentation of the filter in use at the event has been preserved.',actions:[]},
  tiktok:{number:'PROJECT 09',title:'TikTok Effect Collection',tags:['Effect Design','Personal Project'],description:'An exploration of visual and interactive TikTok effects created and published with Effect House.',role:'Effect Creator',tools:'TikTok Effect House',type:'Personal Exploration',highlights:['IT Edition effect','Love and Bunny effects','Simple effect','Several effects have been used in TikTok user videos'],note:'This project is presented as an exploration of creative technology and interactive media.',actions:[['View Instagram Profile','https://instagram.com/nuraism_']]}
};

const canvas=document.querySelector('#stars');
const context=canvas.getContext('2d');
let stars=[];
function setCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(170,Math.floor(innerWidth/8))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.15,a:Math.random()*.65+.15,s:Math.random()*.08+.02}))}
function drawStars(){context.clearRect(0,0,innerWidth,innerHeight);stars.forEach(star=>{star.a+=star.s*(Math.random()>.5?1:-1);star.a=Math.max(.12,Math.min(.85,star.a));context.beginPath();context.arc(star.x,star.y,star.r,0,Math.PI*2);context.fillStyle=`rgba(210,226,255,${star.a})`;context.fill()});requestAnimationFrame(drawStars)}
setCanvas();drawStars();addEventListener('resize',setCanvas);

const words=['Frontend Explorer','Information Systems Student','UI/UX Learner','Creative Effect Maker'];let wordIndex=0,charIndex=0,deleting=false;const typingText=document.querySelector('#typingText');
function type(){const word=words[wordIndex];typingText.textContent=deleting?word.slice(0,--charIndex):word.slice(0,++charIndex);let delay=deleting?45:80;if(!deleting&&charIndex===word.length){deleting=true;delay=1350}else if(deleting&&charIndex===0){deleting=false;wordIndex=(wordIndex+1)%words.length;delay=350}setTimeout(type,delay)}
type();

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...document.querySelectorAll('.nav-link')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-40% 0px -50%'});sections.forEach(section=>sectionObserver.observe(section));

const menu=document.querySelector('#menuButton');const nav=document.querySelector('.floating-nav nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});navLinks.forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(button=>{button.classList.remove('active');button.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');document.querySelectorAll('.tab-panel').forEach(panel=>{const active=panel.dataset.panel===tab.dataset.tab;panel.classList.toggle('active',active);panel.hidden=!active})}));

const modal=document.querySelector('#projectModal');let lastFocus=null;
function openProject(key){const project=projectData[key];if(!project)return;lastFocus=document.activeElement;document.querySelector('#modalNumber').textContent=project.number;document.querySelector('#modalTags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');document.querySelector('#modalTitle').textContent=project.title;document.querySelector('#modalDescription').textContent=project.description;document.querySelector('#modalRole').textContent=project.role;document.querySelector('#modalTools').textContent=project.tools;document.querySelector('#modalType').textContent=project.type;document.querySelector('#modalHighlights').innerHTML=project.highlights.map(item=>`<li>${item}</li>`).join('');document.querySelector('#modalNote').textContent=project.note;document.querySelector('#modalActions').innerHTML=project.actions.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('');modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.modal-close').focus()}
function closeProject(){modal.hidden=true;document.body.style.overflow='';lastFocus?.focus()}
document.querySelectorAll('[data-open-project]').forEach(button=>button.addEventListener('click',()=>openProject(button.dataset.openProject)));document.querySelectorAll('[data-close-modal]').forEach(element=>element.addEventListener('click',closeProject));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeProject()});
document.querySelector('#year').textContent=new Date().getFullYear();
